application: whichcamefirst
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /style
  static_dir: style
  
- url: /js
  static_dir: js

- url: /img
  static_dir: img
  
- url: /lib
  static_dir: lib

- url: /resources
  static_dir: resources

- url: /.*
  script: whichcamefirst.app
  
libraries:
- name: webapp2
  version: "2.5.1"
# builtins:
# - appstats: on
# - deferred: on
# - remote_api: on
